global:
  scrape_interval: 15s  # Set the default scrape interval to 15 seconds

scrape_configs:
  - job_name: 'nodejs-app'  # A unique name for your target
    static_configs:
      - targets: ['host.docker.internal:3000']  # Address where Node.js app metrics are exposed