version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: Root
      POSTGRES_PASSWORD: Root1234
      POSTGRES_DB: outbox_service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - devnet

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - devnet

volumes:
  pgdata:

networks:
  devnet:
    driver: bridge
