{
 "title": "HTTP & Kafka Metrics Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "method",
    "query": {
     "query": "label_values(http_request_total, method)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values(http_request_total, route)"
    }
   },
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_message_latency_seconds, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Latency",
   "type": "timeseries",
   "description": "Shows the percentiles of HTTP request response time",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_response_rate_histogram_bucket{method=\"$method\",route=\"$route\"}[5m])) by (le)) * 1000",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_response_rate_histogram_bucket{method=\"$method\",route=\"$route\"}[5m])) by (le)) * 1000",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_response_rate_histogram_bucket{method=\"$method\",route=\"$route\"}[5m])) by (le)) * 1000",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_response_rate_histogram_bucket{method=\"$method\",route=\"$route\"}[5m])) by (le)) * 1000",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Average Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_response_rate_histogram_sum{method=\"$method\",route=\"$route\"}[1m]) / rate(http_response_rate_histogram_count{method=\"$method\",route=\"$route\"}[1m]) * 1000"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Shows the request rate for HTTP endpoints",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_total{method=\"$method\",route=\"$route\"}[1m]))",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Average Latency (ms) in Queue",
   "type": "timeseries",
   "description": "Average Kafka message processing latency",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kafka_message_latency_seconds_bucket{topic=\"$topic\"}[1m])) by (le)) * 1000"
    }
   ]
  }
 ]
}